# Generated by Django 5.2 on 2025-04-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
