# Generated by Django 5.2 on 2025-04-27 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_bio_alter_doctor_license_number_and_more'),
        ('patients', '0003_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='doctors.doctor', verbose_name='doctor'),
        ),
    ]
