# Generated by Django 5.2 on 2025-04-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_delete_emergencycontact'),
        ('patients', '0004_patient_doctor'),
    ]

    operations = [
    ]
