# Generated by Django 5.2 on 2025-04-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_merge_20250428_1435'),
        ('patients', '0005_merge_20250428_1458'),
    ]

    operations = [
    ]
