# Generated by Django 5.2 on 2025-04-21 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
        ('medications', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient', verbose_name='patient'),
        ),
        migrations.AddField(
            model_name='labresults',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='medical_records.medicalrecord', verbose_name='medical record'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical_records.medicalrecord', verbose_name='medical record'),
        ),
        migrations.AddField(
            model_name='prescriptionmedication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prescriptions', to='medications.medication', verbose_name='medication'),
        ),
        migrations.AddField(
            model_name='prescriptionmedication',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medical_records.prescription', verbose_name='prescription'),
        ),
    ]
