# Generated by Django 5.2 on 2025-04-27 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_initial'),
        ('patients', '0003_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patients.patient', verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='medical_records.medicalrecord', verbose_name='medical record'),
        ),
    ]
