# Generated by Django 5.2 on 2025-04-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatmessage_error_details_chatmessage_is_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_image_generation',
            field=models.BooleanField(default=False),
        ),
    ]
