# Generated by Django 5.2 on 2025-04-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatmessage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
